### ISSUE TITLE
No error during minification

### ISSUE THREAD

**Issue by adam-sokolowski** [hustxiaoc/gulp-minify#10]
Plugin does not emit an error when minified file contains an error, thus its impossible to display an error to user and stop the script.
Changing :
`return new PluginError('gulp-minify', e.toString(e));`
to:
`this.emit('error', new PluginError('gulp-minify', e.toString(e)));`
seem s to be solving a problem

**Comment by kent-remi** [comment]
Error must be returned in callback. I have added this code + added formatting, so, if I get access to the project, i'll commit :)

**Comment by kent-remi** [comment]
Fixed in 0.0.12
