### ISSUE TITLE
ignoreFiles doesn't work

### ISSUE THREAD

**Issue by OZZlE** [hustxiaoc/gulp-minify#14]
I have the following:
```
gulp.task('build-js', function() {
    return gulp.src(['js/src/**/*.js', '!JS_TEMPLATE_FULL.js, !JS_TEMPLATE_MIN.js'])
        .pipe(plumber(function (error) {
            gutil.log(error.message);
            this.emit('end');
        }))
        .pipe(minify({
            noSource: false,
            ignoreFiles: ['min.js']
        }))
        .pipe(gulp.dest('js/dist'))
        .pipe(browserSync.reload({stream:true}))
        ;
});
```

I've tried with: ignoreFiles: ['min.js'] and ignoreFiles: ['.min.js'] (my files are .min) but it still minifies those and appends the -min.js to the file name

**Comment by OZZlE** [comment]
sorry my misstake

**Comment by jeherve** [comment]
I stumbled across this issue when running into similar issues. It turns out I was getting confused by the default behaviour of `gulp-minify`: it creates new files with the `min` extensions. This can be disabled as explained here:
https://github.com/hustxiaoc/gulp-minify/issues/20#issuecomment-300669882

**Comment by howeller** [comment]
@OZZlE What was your solution? I am having the same issue of changing the default to `.min`, but then it it creates a new copy of `.min.min`

**Comment by mreall** [comment]
> @OZZlE What was your solution? I am having the same issue of changing the default to `.min`, but then it it creates a new copy of `.min.min`

@howeller I had the same question. After a bit of testing I was able to get `ignoreFiles` to work by putting an asterisk at the beginning of the file extension, i.e. `ignoreFiles: ['*.min.js']`.
