### ISSUE TITLE
confused as to difference between gulp-minify and gulp-uglify

### ISSUE THREAD

**Issue by ORESoftware** [hustxiaoc/gulp-minify#20]
This may be a dumb request, but quick comparisons sometimes quickly explain.

Could you draw out a quick comparison in the Readme.md for this lib compared to gulp-uglify.

I don't know what the difference is between minification and uglification, only that the former may include concatenation? dunno

**Comment by hustxiaoc** [comment]
`gulp-minify`  supports  custom minify file name,  e.g -min.js or .min.js , and also supports keeping the original source file

**Comment by BartoszBaczek** [comment]
So how do I keep original file name? My gulp task looks like this:

```
gulp.task('minify:app', () => {

    gulp.src('../../dist/app/DotNetTypes-TS/*.js')
    .pipe(minify())
    // .pipe(uglify())
    .pipe(gulp.dest(function(file) {
      return file.base;
    }));
  });
```

and it outputs *-min.js by default.

**Comment by guilhermemar** [comment]
Hi  @BartoszBaczek, you can do that:

```javascript
...
.pipe(minify({ noSource: true,  ext: { min: '.js' } }))
...
```
