### ISSUE TITLE
Let error when I run the task

### ISSUE THREAD

**Issue by luiguild** [hustxiaoc/gulp-minify#21]
I have this gulp task:

```
gulp.task('make:js', function () {
    return gulp.src(files.js.src)
    .pipe($.concat(app.name + '.js'))
    .pipe(jsValidate())
    .pipe($.minify({
        ext:{
            min:'.min.js'
        },
        noSource: true,
        preserveComments: ['some'],
        mangle: false
    }))
    .pipe(gulp.dest(files.js.dest));
});
```

And It's run normally, perfectly... But if I declare my variables using "let" rather than "var", my task starts and pause... forever...

Anyone already seen the same thing or something about this?

**Comment by jwoos** [comment]
I've seen this as well, it doesn't seem to be able to handle ES6 syntax at all. I get the error with `let` and `() => {}`

**Comment by phillipchan2** [comment]
I agree. Using template literals errors out for me.
