### ISSUE TITLE
gulp-minify gets confused by default values for parameters

### ISSUE THREAD

**Issue by fbnlsr** [hustxiaoc/gulp-minify#23]
gulp-minify triggers an error when trying to parse functions that have default values assigned to its parameters.

```javascript
function constructCampaign(campaign, output_description = false) {
...
}
```

Triggers this error:

`[12:05:04] Plumber found unhandled error:
 Error in plugin 'gulp-minify'
www/js/script.js
SyntaxError: Unexpected token operator «=», expected punc «,» (line: 4512, col: 56, pos: 222911`

**Comment by hustxiaoc** [comment]
You should probably add a babel task before it.
