### ISSUE TITLE
gulp-util is deprecated - should be migrated away from

### ISSUE THREAD

**Issue by adamxtokyo** [hustxiaoc/gulp-minify#36]
The gulp team recommends upgrading migrating away from gulp-util using the guidelines in the article below:

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by rbatllet** [comment]
This could be the reason why it no longer works

See: https://github.com/hustxiaoc/gulp-minify/issues/37

**Comment by adamxtokyo** [comment]
Yeup. More than likely related.

**Comment by hustxiaoc** [comment]
https://github.com/hustxiaoc/gulp-minify/pull/34

**Comment by hustxiaoc** [comment]
fixed https://github.com/hustxiaoc/gulp-minify/pull/34
