### ISSUE TITLE
 New dependency name: uglify-es => terser

### ISSUE THREAD

**Issue by fabiosantoscode** [hustxiaoc/gulp-minify#43]
There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

**Comment by hustxiaoc** [comment]
Hi, can i know on what purpose？

**Comment by fabiosantoscode** [comment]
Hello :) Sorry for the duplicate issues.

uglify-es, which is a branch of the UglifyJS2 repository, is now unmaintained (https://github.com/mishoo/UglifyJS2/issues/2842#issuecomment-359680663), and the new maintained fork is under my account.

Others are adopting the terser fork, namely webpack (https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/296) and parcel (https://github.com/parcel-bundler/parcel/pull/1382).

You can choose to follow us to terser, remain using uglify-es (which I don't recommend since it's unmaintained) or use uglifyjs (which is maintained but only works with ES5 code). It's up to you :)

Cheers!

**Comment by kzc** [comment]
> uglify-es => terser #1

@fabiosantoscode I've got to ask - what does the `#1` mean? It's not an Issue or PR number.

**Comment by hustxiaoc** [comment]
OK，i'll replace it with `terser`
