### ISSUE TITLE
Parameter "compress: false" no longer works in 0.0.9

### ISSUE THREAD

**Issue by nedex** [hustxiaoc/gulp-minify#8]
The attribute is ignored in 0.0.9 (it is working in 0.0.7)

**Comment by hustxiaoc** [comment]
@nedex , could you please make a pull request to fix this? thanks ~

**Comment by nedex** [comment]
It's resolved in 0.0.10.
The options were overridden and without `options: {beautify: true}` was not possible to check the code.
Good work!
